# Generated by Django 4.1.3 on 2022-11-04 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_cat_age"),
        ("main_app", "0002_feeding"),
    ]

    operations = []
